server:
  port: 80
spring:
  profiles:
    active: dev #部署环境 prod:生产环境(不打印sql) dev:开发环境(打印sql)
  #数据源
  datasource:
    url: jdbc:mysql://192.168.31.195:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #缓存
  redis:
    host: 192.168.31.195
    port: 6379
    database: 0
    password: e593813e7d4c729da37e5e41fe760b0e
    timeout: 4500ms
    lettuce:
      pool:
        max-active: 8  #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 5    #连接池中的最大空闲连接
        min-idle: 0    #连接池中的最小空闲连接
  #es搜索引擎
  elasticsearch:
    uris: http://192.168.31.195:9200
#mybatis配置信息
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
#系统监控
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
#API在线文档
springdoc:
  api-docs:
    groups:
      enabled: true
#Redis自定义key
redis:
  key:
    prefix:
      auth-code: "portal:authCode:"
#JWT设置
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: youkongyi-mall-secret #JWT加解密使用的密钥
  expiration: 604800000  #JWT的超期限时间(毫秒)
  tokenHead: 'Bearer ' #JWT负载中拿到开头