server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.0.184:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
